import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { EnquiryModal } from "./components/modal/enquiry-modal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bestinationz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EnquiryModal/>
        {children}</body>
    </html>
  );
}
